# Lista de cadre: id, referinte, descrierea scenei
STYLE = """Photograph of a handmade layered cut-paper diorama, a miniature paper theater, in exactly the same style as the style reference image: every element cut from textured coloured card and tissue paper, real soft drop shadows between the layers, visible paper fibres, slightly uneven cut edges, shallow depth of field. The stage is framed by cardboard side-wings in ink blue, brick red, mustard and sage. Palette: ink blue #1F2A44, violet-blue dusk sky, ochre lamplight #F2C57C, sage and brick walls, natural cardboard, charcoal-black silhouettes, and pale pink #E8B4B8 used ONLY for the girl's shoes, her bows and ice cream. Cinematic 16:9 composition with calm negative space. No text, no letters, no numbers, no writing anywhere."""

GIRL = "THE GIRL must be exactly the girl from the character reference: about five, two long brown braids with small pale pink bows, navy dress with white collar, white socks, pale pink shoes each with a tiny paper butterfly, round face, dot eyes, rosy cheeks."
BOY = "THE GROUP LEADER must be exactly the boy from the character reference: a young child about six, only slightly taller than the other kids, short brown hair, mustard knitted sweater, blue trousers."
DAD = "THE FATHER must be exactly the man from the character reference: short brown beard, round thin wire glasses, grey felt overcoat."
ROOM = "Setting: an old kindergarten room in Alba Iulia with sage walls, small wooden chairs, a floor lamp with a paper shade, a low wooden table with a plain cardboard box with a coin slot, an orange paper goldfish in a round cellophane bowl on the windowsill, and a big window showing a paper skyline of old Transylvanian roofs and church spires."

G = ["referinte/fetita_portret.png"]
GS = ["referinte/fetita_sezand.png"]
B = ["referinte/sef_portret.png"]
D = ["referinte/tata_portret.png"]

SHOTS = [
 ("00_titlu", [], "Wide establishing shot at dusk: a paper-cut panorama of Alba Iulia seen as a theater stage, the star-shaped white Vauban fortress walls and the cathedral towers on a hill, small houses below, and in the foreground a little kindergarten building with one warmly lit window. First stars appear in a violet-blue sky. Very calm, lots of sky space at the top for a title to be added later."),
 ("01a_sala", G+B, ROOM + " Warm dusk, lamp lit. About twenty small children made of coloured paper sit on the little chairs in a semicircle around the low table with the cardboard box. The girl sits at the edge of the semicircle nearest the lamp. The boy sits among the others. Cozy and peaceful. The children are an ordinary group, all fully coloured, nobody stands behind them. IMPORTANT: in this scene there are NO black silhouettes at all; every child is a fully coloured paper figure with a face."),
 ("01b_banuti", [], "Close-up on the low wooden table in warm lamplight: several small paper children's hands drop round golden paper coins one by one into the slot of a plain cardboard box; the hands are child-sized, in scale with the box, coming from children standing around the table. Shallow depth of field, the kindergarten room blurred behind."),
 ("01c_amintiri", [], "The kindergarten windowsill in warm evening light, like a little paper still life: a jar of coloured paper pencils, the orange paper goldfish in its round cellophane bowl, and through the window a red paper ball flying high over a paper garden fence into the dusk."),
 ("02a_propunerea", G+B, ROOM + " The boy stands up on a little chair in the middle of the room, arms spread wide, speaking loudly and confidently. The other paper children look up at him eagerly. The girl sits at the side near the lamp, looking up at him a little uncertainly."),
 ("02b_ura", B, ROOM + " Above the children floats a big fluffy cloud of white tissue paper filled with pale pink paper ice-cream cones. The paper children cheer and clap with raised happy faces; the boy stands on his chair, arms wide, below the cloud. IMPORTANT: in this scene there are NO black silhouettes at all; every child is a fully coloured paper figure with a face."),
 ("02c_craciun", GS, "Medium close-up of the girl sitting on her small wooden chair in lamplight, thinking, her chin on her hand. Above her head a small tissue-paper thought bubble shows a tiny paper Christmas tree on one side, a long winding paper path, and another tiny Christmas tree far away on the other side. Behind her, out of focus, other coloured paper children clap."+" IMPORTANT: in this scene there are NO black silhouettes at all; every child is a fully coloured paper figure with a face. " + ROOM),
 ("03a_foaia", B, ROOM + " Light slightly cooler. The boy stands on his chair holding up a single sheet of white paper covered in tiny unreadable scribbles, asking for a vote. The children look at the sheet."),
 ("03b_votul", GS, ROOM + " Behind the row of small wooden chairs stand twenty children rendered as flat charcoal-black paper silhouettes in two rows, all raising their hands high in a vote. In the foreground, in the pool of warm lamplight, the girl sits on her chair, hands in her lap, not raising her hand, looking down at her butterfly shoes. The contrast between the dark silhouettes and the one coloured girl is the heart of the image."),
 ("03c_pantofii", [], "Extreme close-up, low angle, of a little girl's feet on the wooden floor: white socks and pale pink paper shoes each with a tiny paper butterfly, the legs of a small wooden chair beside them, warm lamplight, very shallow depth of field."),
 ("04a_asteptarea", G, ROOM + " Two weeks later. Blue evening light, the lamp is dimmer. Seen from behind, several paper children including the girl stand at the big window with their hands on the sill, looking out and waiting. A round paper wall clock. The cardboard box on the table. No ice cream anywhere."),
 ("04b_investitia", B, ROOM + " Cool blue light. The boy stands by the table, reassuring the other children with an open hand. From the cardboard box, a thin trail of paper coins floats away out of the door towards the hand of a much taller older child seen only as a black paper silhouette from the waist down at the doorway."),
 ("05a_cutia_goala", [], ROOM + " Three months later, cold blue light, lamp off. Close on the table: the cardboard box stands open and completely empty. On the windowsill the orange paper goldfish floats limp and sad in its bowl, a tiny empty food tin beside it. An empty jar where the pencils used to be."),
 ("05b_clasa_a_sasea", B, ROOM + " Cold blue light. The boy stands on his chair pointing up excitedly at an even taller black paper silhouette of an older schoolchild seen only from the waist down, towering over the little chairs. The empty open cardboard box on the table."),
 ("05c_cat_de_tarziu", G+B, ROOM + " Cold blue light. The girl stands next to the table looking up at the boy, asking a serious question. The boy stands on his chair, one finger on his chin, thinking, looking far away. Behind the window the first night sky."),
 ("06a_sirul", [], ROOM + " Night blue light. A long receding line of ever-taller charcoal-black paper silhouettes seen only from the waist down, each handing down a sheet of white paper to the next; the sheets pile up unread on the floor around the empty open cardboard box. Rhythmic, repetitive composition."),
 ("06b_numaratoarea", GS, ROOM + " Night blue light. The girl sits apart on her small chair, counting on her fingers with a worried face. Behind her, four very tall black paper silhouettes of older children of increasing height stand in a row, seen from the waist down. Piles of unread white papers, the empty box."),
 ("07a_anii", [], "Paper-cut time-passing tableau: the same little kindergarten building in Alba Iulia shown on one wide stage as four seasons side by side from left to right, spring blossoms, summer green, autumn leaves, winter snow, while a paper tree beside it grows taller from left to right. Cool, nostalgic evening light, the fortress walls in the background."),
 ("07b_tatal", D+G, ROOM + " Thirty years later, the same room but slightly faded, cold morning light. The father stands holding the hand of his little daughter, who looks exactly like the girl from the reference (same braids, bows, navy dress, butterfly shoes). They face the same old cardboard box on the low table, now worn and patched with tape. A kindergarten teacher stands beside the table, seen as a soft grey paper figure."),
 ("07c_amintirea", D, "Close-up of the father, seen from the chest up in the faded kindergarten room, looking down at his own big hands with a stunned, remembering expression. Behind him, like a pale ghostly tissue-paper memory, a row of small children's raised hands and colourful little chairs. Cool light."),
 ("08a_dormitorul", D+G, "Night, a small paper-cut child's bedroom: moonlight through the window over the paper skyline of Alba Iulia spires. The little girl lies in bed under a patchwork paper quilt, looking up at her father, who sits in silence on the edge of the bed. Soft silver moonlight falls on both their faces. A small bedside lamp is off. Quiet and tender."),
 ("08b_soapta", G, "Close-up of the little girl in bed, moonlit, whispering, one small hand held slightly up beside her pillow as if showing it was never raised. Patchwork paper quilt, silver moonlight on her face, dark blue room."),
 ("08c_tacerea", D, "Close-up of the father sitting on the edge of the bed at night, silver moonlight from the window on his bearded face and round glasses, looking down in silence, full of regret. Dark blue room, the window behind with paper spires."),
 ("09_final", [], "Night windowsill in a paper-cut bedroom: a single pale pink paper ice-cream cone slowly melting, a thin pink drip running down the sill. Through the window, the paper skyline of Alba Iulia with the fortress walls under the moon, most of the little windows already dark. Very calm, empty space around the ice cream."),
]
